import { Event } from '../types';

export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'Rooftop Jazz Night',
    description: 'Join us for an evening of jazz and drinks on a beautiful rooftop overlooking the city.',
    location: {
      address: '123 Main St, San Francisco, CA',
      coordinates: {
        latitude: 37.7749,
        longitude: -122.4194,
      },
    },
    date: '2025-06-15',
    time: '7:00 PM',
    imageURL: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80',
    hostId: 'user1',
    attendees: [
      { id: 'user1', photoURL: 'https://randomuser.me/api/portraits/men/32.jpg' },
      { id: 'user2', photoURL: 'https://randomuser.me/api/portraits/women/44.jpg' },
      { id: 'user3', photoURL: 'https://randomuser.me/api/portraits/men/76.jpg' },
      { id: 'user4', photoURL: 'https://randomuser.me/api/portraits/women/33.jpg' },
    ],
    interestedUsers: ['user2', 'user5', 'user7'],
    maxAttendees: 30,
    category: 'music',
    tags: ['jazz', 'rooftop', 'drinks', 'live music'],
    isPrivate: false,
    createdAt: '2025-05-01T10:30:00Z',
    updatedAt: '2025-05-05T14:15:00Z',
  },
  {
    id: '2',
    title: 'Tech Startup Networking',
    description: 'Connect with other tech entrepreneurs and investors in a casual setting.',
    location: {
      address: '456 Market St, San Francisco, CA',
      coordinates: {
        latitude: 37.7897,
        longitude: -122.4000,
      },
    },
    date: '2025-06-20',
    time: '6:30 PM',
    imageURL: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80',
    hostId: 'user5',
    attendees: [
      { id: 'user5', photoURL: 'https://randomuser.me/api/portraits/men/42.jpg' },
      { id: 'user6', photoURL: 'https://randomuser.me/api/portraits/women/24.jpg' },
      { id: 'user7', photoURL: 'https://randomuser.me/api/portraits/men/36.jpg' },
    ],
    interestedUsers: ['user1', 'user8', 'user9'],
    maxAttendees: 50,
    category: 'networking',
    tags: ['tech', 'startup', 'networking', 'entrepreneurs'],
    isPrivate: false,
    createdAt: '2025-05-02T09:45:00Z',
    updatedAt: '2025-05-06T11:20:00Z',
  },
  {
    id: '3',
    title: 'Yoga in the Park',
    description: 'Start your day with a rejuvenating yoga session in the park. All levels welcome!',
    location: {
      address: 'Golden Gate Park, San Francisco, CA',
      coordinates: {
        latitude: 37.7694,
        longitude: -122.4862,
      },
    },
    date: '2025-06-18',
    time: '8:00 AM',
    imageURL: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80',
    hostId: 'user8',
    attendees: [
      { id: 'user8', photoURL: 'https://randomuser.me/api/portraits/women/65.jpg' },
      { id: 'user2', photoURL: 'https://randomuser.me/api/portraits/women/44.jpg' },
      { id: 'user9', photoURL: 'https://randomuser.me/api/portraits/men/18.jpg' },
      { id: 'user10', photoURL: 'https://randomuser.me/api/portraits/women/54.jpg' },
      { id: 'user11', photoURL: 'https://randomuser.me/api/portraits/men/67.jpg' },
    ],
    interestedUsers: ['user3', 'user4', 'user12'],
    maxAttendees: 25,
    category: 'fitness',
    tags: ['yoga', 'outdoors', 'wellness', 'morning'],
    isPrivate: false,
    createdAt: '2025-05-03T15:20:00Z',
    updatedAt: '2025-05-07T10:10:00Z',
  },
  {
    id: '4',
    title: 'Cocktail Making Class',
    description: 'Learn how to make classic and creative cocktails with expert mixologists.',
    location: {
      address: '789 Valencia St, San Francisco, CA',
      coordinates: {
        latitude: 37.7617,
        longitude: -122.4216,
      },
    },
    date: '2025-06-25',
    time: '7:30 PM',
    imageURL: 'https://images.unsplash.com/photo-1516997121675-4c2d1684aa3e?ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80',
    hostId: 'user12',
    attendees: [
      { id: 'user12', photoURL: 'https://randomuser.me/api/portraits/women/28.jpg' },
      { id: 'user13', photoURL: 'https://randomuser.me/api/portraits/men/45.jpg' },
    ],
    interestedUsers: ['user5', 'user7', 'user10', 'user11'],
    maxAttendees: 15,
    category: 'food-drinks',
    tags: ['cocktails', 'class', 'mixology', 'drinks'],
    isPrivate: false,
    createdAt: '2025-05-04T13:40:00Z',
    updatedAt: '2025-05-08T16:30:00Z',
  },
  {
    id: '5',
    title: 'Board Game Night',
    description: 'Casual board game night with a variety of games for all skill levels.',
    location: {
      address: '321 Hayes St, San Francisco, CA',
      coordinates: {
        latitude: 37.7764,
        longitude: -122.4242,
      },
    },
    date: '2025-06-19',
    time: '6:00 PM',
    imageURL: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80',
    hostId: 'user7',
    attendees: [
      { id: 'user7', photoURL: 'https://randomuser.me/api/portraits/men/36.jpg' },
      { id: 'user14', photoURL: 'https://randomuser.me/api/portraits/women/71.jpg' },
      { id: 'user15', photoURL: 'https://randomuser.me/api/portraits/men/29.jpg' },
      { id: 'user16', photoURL: 'https://randomuser.me/api/portraits/women/17.jpg' },
      { id: 'user17', photoURL: 'https://randomuser.me/api/portraits/men/52.jpg' },
      { id: 'user18', photoURL: 'https://randomuser.me/api/portraits/women/39.jpg' },
    ],
    interestedUsers: ['user1', 'user6', 'user8'],
    maxAttendees: 20,
    category: 'games',
    tags: ['board games', 'social', 'games', 'casual'],
    isPrivate: false,
    createdAt: '2025-05-05T19:15:00Z',
    updatedAt: '2025-05-09T12:25:00Z',
  },
  {
    id: '6',
    title: 'Photography Walk',
    description: 'Explore the city while taking photos and learning photography tips from professionals.',
    location: {
      address: 'Embarcadero, San Francisco, CA',
      coordinates: {
        latitude: 37.7955,
        longitude: -122.3937,
      },
    },
    date: '2025-06-22',
    time: '10:00 AM',
    imageURL: 'https://images.unsplash.com/photo-1531845116688-48819b3b68d9?ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80',
    hostId: 'user3',
    attendees: [
      { id: 'user3', photoURL: 'https://randomuser.me/api/portraits/men/76.jpg' },
      { id: 'user19', photoURL: 'https://randomuser.me/api/portraits/women/52.jpg' },
      { id: 'user20', photoURL: 'https://randomuser.me/api/portraits/men/84.jpg' },
    ],
    interestedUsers: ['user2', 'user9', 'user15'],
    maxAttendees: 12,
    category: 'art',
    tags: ['photography', 'walking tour', 'city', 'art'],
    isPrivate: false,
    createdAt: '2025-05-06T11:50:00Z',
    updatedAt: '2025-05-10T17:40:00Z',
  },
  {
    id: '7',
    title: 'Wine Tasting Evening',
    description: 'Taste a selection of wines from local vineyards with an expert sommelier.',
    location: {
      address: '555 California St, San Francisco, CA',
      coordinates: {
        latitude: 37.7923,
        longitude: -122.4036,
      },
    },
    date: '2025-06-28',
    time: '6:00 PM',
    imageURL: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80',
    hostId: 'user14',
    attendees: [
      { id: 'user14', photoURL: 'https://randomuser.me/api/portraits/women/71.jpg' },
      { id: 'user21', photoURL: 'https://randomuser.me/api/portraits/men/22.jpg' },
      { id: 'user22', photoURL: 'https://randomuser.me/api/portraits/women/88.jpg' },
      { id: 'user23', photoURL: 'https://randomuser.me/api/portraits/men/63.jpg' },
    ],
    interestedUsers: ['user4', 'user12', 'user16', 'user18'],
    maxAttendees: 18,
    category: 'food-drinks',
    tags: ['wine', 'tasting', 'sommelier', 'evening'],
    isPrivate: false,
    createdAt: '2025-05-07T14:25:00Z',
    updatedAt: '2025-05-11T09:35:00Z',
  },
  {
    id: '8',
    title: 'Coding Workshop: React Native',
    description: 'Learn how to build mobile apps with React Native in this hands-on workshop.',
    location: {
      address: '888 Brannan St, San Francisco, CA',
      coordinates: {
        latitude: 37.7721,
        longitude: -122.4051,
      },
    },
    date: '2025-06-24',
    time: '11:00 AM',
    imageURL: 'https://images.unsplash.com/photo-1523800503107-5bc3ba2a6f81?ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80',
    hostId: 'user24',
    attendees: [
      { id: 'user24', photoURL: 'https://randomuser.me/api/portraits/men/10.jpg' },
      { id: 'user25', photoURL: 'https://randomuser.me/api/portraits/women/6.jpg' },
    ],
    interestedUsers: ['user5', 'user7', 'user13', 'user20'],
    maxAttendees: 25,
    category: 'tech',
    tags: ['coding', 'workshop', 'react native', 'mobile'],
    isPrivate: false,
    createdAt: '2025-05-08T10:10:00Z',
    updatedAt: '2025-05-12T15:45:00Z',
  }
];

export default { mockEvents }; 